version: '3.8'

services:
  postgres:
    image: postgres:13 # Usar uma versão específica é uma boa prática
    container_name: policia_db_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data: